const data = [
    {name : "Agriculture", value : "agriculture"},
    {name : "Animal", value : "animal"},
    {name : "Appliances", value : "appliances"},
    {name : "Art & Abstract", value : "art_abstract"},
    {name : "Background & Patterns", value : "background_patterns"},
    {name : "Buildings", value : "buildings"},
    {name : "Business", value : "business"},
    {name : "Clothing & Accessories", value : "clothing_accessories"},
    {name : "Crime & Security", value : "crime_security"},
    {name : "Culture & Religion", value : "culture_religion"},
    {name : "E-commerce & Shopping", value : "e-commerce_shopping"},
    {name : "Design & Development", value : "design_development"},
    {name : "Editorial", value : "editorial"},
    {name : "Entertainment", value : "entertainment"},
    {name : "Festival & Days", value : "festival_days"},
    {name : "Files & Folders", value : "files_folders"},
    {name : "Food & Drink", value : "food_drink"},
    {name : "Gym & Fitness", value : "gym_fitness"},
    {name : "Healthcare & Medical", value : "healthcare_medical"},
    {name : "Holidays", value : "holidays"},
    {name : "Industry", value : "industry"},
    {name : "Interiors", value : "interiors"},
    {name : "Logos", value : "logos"},
    {name : "Maps & Navigation", value : "maps_navigation"},
    {name : "Miscellaneous", value : "miscellaneous"},
    {name : "Network & Communication", value : "network_communication"},
    {name : "People", value : "people"},
    {name : "Politics", value : "politics"},
    {name : "Relationship", value : "relationship"},
    {name : "School & Education", value : "school_education"},
    {name : "Science & Technology", value : "science_technology"},
    {name : "Web", value : "web"},
    {name : "Services", value : "services"},
    {name : "Sports & Games", value : "sports_games"},
    {name : "Tools & Equipment", value : "tools_equipment"},
    {name : "User Interface", value : "user_interface"},
    {name : "Vehicle", value : "vehicle"},
]

export default data;
